// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catalog.proto

package org.mrk.grpc.catalog;

public interface BundleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Bundle)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 quantity = 1;</code>
   */
  long getQuantity();

  /**
   * <code>optional float price = 2;</code>
   */
  float getPrice();
}
