// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catalog.proto

package org.mrk.grpc.catalog;

public interface CatalogOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Catalog)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string catalogId = 1;</code>
   */
  java.lang.String getCatalogId();
  /**
   * <code>optional string catalogId = 1;</code>
   */
  com.google.protobuf.ByteString
      getCatalogIdBytes();

  /**
   * <code>optional string catalogName = 2;</code>
   */
  java.lang.String getCatalogName();
  /**
   * <code>optional string catalogName = 2;</code>
   */
  com.google.protobuf.ByteString
      getCatalogNameBytes();

  /**
   * <code>repeated .CatalogItem catalogItems = 3;</code>
   */
  java.util.List<org.mrk.grpc.catalog.CatalogItem> 
      getCatalogItemsList();
  /**
   * <code>repeated .CatalogItem catalogItems = 3;</code>
   */
  org.mrk.grpc.catalog.CatalogItem getCatalogItems(int index);
  /**
   * <code>repeated .CatalogItem catalogItems = 3;</code>
   */
  int getCatalogItemsCount();
  /**
   * <code>repeated .CatalogItem catalogItems = 3;</code>
   */
  java.util.List<? extends org.mrk.grpc.catalog.CatalogItemOrBuilder> 
      getCatalogItemsOrBuilderList();
  /**
   * <code>repeated .CatalogItem catalogItems = 3;</code>
   */
  org.mrk.grpc.catalog.CatalogItemOrBuilder getCatalogItemsOrBuilder(
      int index);
}
