// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catalog.proto

package org.mrk.grpc.catalog;

public interface CatalogItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CatalogItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .Product product = 1;</code>
   */
  boolean hasProduct();
  /**
   * <code>optional .Product product = 1;</code>
   */
  org.mrk.grpc.catalog.Product getProduct();
  /**
   * <code>optional .Product product = 1;</code>
   */
  org.mrk.grpc.catalog.ProductOrBuilder getProductOrBuilder();

  /**
   * <code>repeated .Bundle bundles = 2;</code>
   */
  java.util.List<org.mrk.grpc.catalog.Bundle> 
      getBundlesList();
  /**
   * <code>repeated .Bundle bundles = 2;</code>
   */
  org.mrk.grpc.catalog.Bundle getBundles(int index);
  /**
   * <code>repeated .Bundle bundles = 2;</code>
   */
  int getBundlesCount();
  /**
   * <code>repeated .Bundle bundles = 2;</code>
   */
  java.util.List<? extends org.mrk.grpc.catalog.BundleOrBuilder> 
      getBundlesOrBuilderList();
  /**
   * <code>repeated .Bundle bundles = 2;</code>
   */
  org.mrk.grpc.catalog.BundleOrBuilder getBundlesOrBuilder(
      int index);
}
