// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catalog.proto

package org.mrk.grpc.catalog;

/**
 * Protobuf type {@code CatalogItem}
 */
public  final class CatalogItem extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CatalogItem)
    CatalogItemOrBuilder {
  // Use CatalogItem.newBuilder() to construct.
  private CatalogItem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CatalogItem() {
    bundles_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private CatalogItem(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            org.mrk.grpc.catalog.Product.Builder subBuilder = null;
            if (product_ != null) {
              subBuilder = product_.toBuilder();
            }
            product_ = input.readMessage(org.mrk.grpc.catalog.Product.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(product_);
              product_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              bundles_ = new java.util.ArrayList<org.mrk.grpc.catalog.Bundle>();
              mutable_bitField0_ |= 0x00000002;
            }
            bundles_.add(
                input.readMessage(org.mrk.grpc.catalog.Bundle.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        bundles_ = java.util.Collections.unmodifiableList(bundles_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.mrk.grpc.catalog.CatalogProto.internal_static_CatalogItem_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.mrk.grpc.catalog.CatalogProto.internal_static_CatalogItem_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.mrk.grpc.catalog.CatalogItem.class, org.mrk.grpc.catalog.CatalogItem.Builder.class);
  }

  private int bitField0_;
  public static final int PRODUCT_FIELD_NUMBER = 1;
  private org.mrk.grpc.catalog.Product product_;
  /**
   * <code>optional .Product product = 1;</code>
   */
  public boolean hasProduct() {
    return product_ != null;
  }
  /**
   * <code>optional .Product product = 1;</code>
   */
  public org.mrk.grpc.catalog.Product getProduct() {
    return product_ == null ? org.mrk.grpc.catalog.Product.getDefaultInstance() : product_;
  }
  /**
   * <code>optional .Product product = 1;</code>
   */
  public org.mrk.grpc.catalog.ProductOrBuilder getProductOrBuilder() {
    return getProduct();
  }

  public static final int BUNDLES_FIELD_NUMBER = 2;
  private java.util.List<org.mrk.grpc.catalog.Bundle> bundles_;
  /**
   * <code>repeated .Bundle bundles = 2;</code>
   */
  public java.util.List<org.mrk.grpc.catalog.Bundle> getBundlesList() {
    return bundles_;
  }
  /**
   * <code>repeated .Bundle bundles = 2;</code>
   */
  public java.util.List<? extends org.mrk.grpc.catalog.BundleOrBuilder> 
      getBundlesOrBuilderList() {
    return bundles_;
  }
  /**
   * <code>repeated .Bundle bundles = 2;</code>
   */
  public int getBundlesCount() {
    return bundles_.size();
  }
  /**
   * <code>repeated .Bundle bundles = 2;</code>
   */
  public org.mrk.grpc.catalog.Bundle getBundles(int index) {
    return bundles_.get(index);
  }
  /**
   * <code>repeated .Bundle bundles = 2;</code>
   */
  public org.mrk.grpc.catalog.BundleOrBuilder getBundlesOrBuilder(
      int index) {
    return bundles_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (product_ != null) {
      output.writeMessage(1, getProduct());
    }
    for (int i = 0; i < bundles_.size(); i++) {
      output.writeMessage(2, bundles_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (product_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getProduct());
    }
    for (int i = 0; i < bundles_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, bundles_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.mrk.grpc.catalog.CatalogItem)) {
      return super.equals(obj);
    }
    org.mrk.grpc.catalog.CatalogItem other = (org.mrk.grpc.catalog.CatalogItem) obj;

    boolean result = true;
    result = result && (hasProduct() == other.hasProduct());
    if (hasProduct()) {
      result = result && getProduct()
          .equals(other.getProduct());
    }
    result = result && getBundlesList()
        .equals(other.getBundlesList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (hasProduct()) {
      hash = (37 * hash) + PRODUCT_FIELD_NUMBER;
      hash = (53 * hash) + getProduct().hashCode();
    }
    if (getBundlesCount() > 0) {
      hash = (37 * hash) + BUNDLES_FIELD_NUMBER;
      hash = (53 * hash) + getBundlesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.mrk.grpc.catalog.CatalogItem parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mrk.grpc.catalog.CatalogItem parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mrk.grpc.catalog.CatalogItem parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mrk.grpc.catalog.CatalogItem parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mrk.grpc.catalog.CatalogItem parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mrk.grpc.catalog.CatalogItem parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mrk.grpc.catalog.CatalogItem parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.mrk.grpc.catalog.CatalogItem parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mrk.grpc.catalog.CatalogItem parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mrk.grpc.catalog.CatalogItem parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.mrk.grpc.catalog.CatalogItem prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CatalogItem}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CatalogItem)
      org.mrk.grpc.catalog.CatalogItemOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.mrk.grpc.catalog.CatalogProto.internal_static_CatalogItem_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.mrk.grpc.catalog.CatalogProto.internal_static_CatalogItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.mrk.grpc.catalog.CatalogItem.class, org.mrk.grpc.catalog.CatalogItem.Builder.class);
    }

    // Construct using org.mrk.grpc.catalog.CatalogItem.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getBundlesFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (productBuilder_ == null) {
        product_ = null;
      } else {
        product_ = null;
        productBuilder_ = null;
      }
      if (bundlesBuilder_ == null) {
        bundles_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        bundlesBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.mrk.grpc.catalog.CatalogProto.internal_static_CatalogItem_descriptor;
    }

    public org.mrk.grpc.catalog.CatalogItem getDefaultInstanceForType() {
      return org.mrk.grpc.catalog.CatalogItem.getDefaultInstance();
    }

    public org.mrk.grpc.catalog.CatalogItem build() {
      org.mrk.grpc.catalog.CatalogItem result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.mrk.grpc.catalog.CatalogItem buildPartial() {
      org.mrk.grpc.catalog.CatalogItem result = new org.mrk.grpc.catalog.CatalogItem(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (productBuilder_ == null) {
        result.product_ = product_;
      } else {
        result.product_ = productBuilder_.build();
      }
      if (bundlesBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          bundles_ = java.util.Collections.unmodifiableList(bundles_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.bundles_ = bundles_;
      } else {
        result.bundles_ = bundlesBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.mrk.grpc.catalog.CatalogItem) {
        return mergeFrom((org.mrk.grpc.catalog.CatalogItem)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.mrk.grpc.catalog.CatalogItem other) {
      if (other == org.mrk.grpc.catalog.CatalogItem.getDefaultInstance()) return this;
      if (other.hasProduct()) {
        mergeProduct(other.getProduct());
      }
      if (bundlesBuilder_ == null) {
        if (!other.bundles_.isEmpty()) {
          if (bundles_.isEmpty()) {
            bundles_ = other.bundles_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureBundlesIsMutable();
            bundles_.addAll(other.bundles_);
          }
          onChanged();
        }
      } else {
        if (!other.bundles_.isEmpty()) {
          if (bundlesBuilder_.isEmpty()) {
            bundlesBuilder_.dispose();
            bundlesBuilder_ = null;
            bundles_ = other.bundles_;
            bitField0_ = (bitField0_ & ~0x00000002);
            bundlesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getBundlesFieldBuilder() : null;
          } else {
            bundlesBuilder_.addAllMessages(other.bundles_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.mrk.grpc.catalog.CatalogItem parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.mrk.grpc.catalog.CatalogItem) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private org.mrk.grpc.catalog.Product product_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mrk.grpc.catalog.Product, org.mrk.grpc.catalog.Product.Builder, org.mrk.grpc.catalog.ProductOrBuilder> productBuilder_;
    /**
     * <code>optional .Product product = 1;</code>
     */
    public boolean hasProduct() {
      return productBuilder_ != null || product_ != null;
    }
    /**
     * <code>optional .Product product = 1;</code>
     */
    public org.mrk.grpc.catalog.Product getProduct() {
      if (productBuilder_ == null) {
        return product_ == null ? org.mrk.grpc.catalog.Product.getDefaultInstance() : product_;
      } else {
        return productBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .Product product = 1;</code>
     */
    public Builder setProduct(org.mrk.grpc.catalog.Product value) {
      if (productBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        product_ = value;
        onChanged();
      } else {
        productBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .Product product = 1;</code>
     */
    public Builder setProduct(
        org.mrk.grpc.catalog.Product.Builder builderForValue) {
      if (productBuilder_ == null) {
        product_ = builderForValue.build();
        onChanged();
      } else {
        productBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .Product product = 1;</code>
     */
    public Builder mergeProduct(org.mrk.grpc.catalog.Product value) {
      if (productBuilder_ == null) {
        if (product_ != null) {
          product_ =
            org.mrk.grpc.catalog.Product.newBuilder(product_).mergeFrom(value).buildPartial();
        } else {
          product_ = value;
        }
        onChanged();
      } else {
        productBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .Product product = 1;</code>
     */
    public Builder clearProduct() {
      if (productBuilder_ == null) {
        product_ = null;
        onChanged();
      } else {
        product_ = null;
        productBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .Product product = 1;</code>
     */
    public org.mrk.grpc.catalog.Product.Builder getProductBuilder() {
      
      onChanged();
      return getProductFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .Product product = 1;</code>
     */
    public org.mrk.grpc.catalog.ProductOrBuilder getProductOrBuilder() {
      if (productBuilder_ != null) {
        return productBuilder_.getMessageOrBuilder();
      } else {
        return product_ == null ?
            org.mrk.grpc.catalog.Product.getDefaultInstance() : product_;
      }
    }
    /**
     * <code>optional .Product product = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mrk.grpc.catalog.Product, org.mrk.grpc.catalog.Product.Builder, org.mrk.grpc.catalog.ProductOrBuilder> 
        getProductFieldBuilder() {
      if (productBuilder_ == null) {
        productBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mrk.grpc.catalog.Product, org.mrk.grpc.catalog.Product.Builder, org.mrk.grpc.catalog.ProductOrBuilder>(
                getProduct(),
                getParentForChildren(),
                isClean());
        product_ = null;
      }
      return productBuilder_;
    }

    private java.util.List<org.mrk.grpc.catalog.Bundle> bundles_ =
      java.util.Collections.emptyList();
    private void ensureBundlesIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        bundles_ = new java.util.ArrayList<org.mrk.grpc.catalog.Bundle>(bundles_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.mrk.grpc.catalog.Bundle, org.mrk.grpc.catalog.Bundle.Builder, org.mrk.grpc.catalog.BundleOrBuilder> bundlesBuilder_;

    /**
     * <code>repeated .Bundle bundles = 2;</code>
     */
    public java.util.List<org.mrk.grpc.catalog.Bundle> getBundlesList() {
      if (bundlesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(bundles_);
      } else {
        return bundlesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Bundle bundles = 2;</code>
     */
    public int getBundlesCount() {
      if (bundlesBuilder_ == null) {
        return bundles_.size();
      } else {
        return bundlesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Bundle bundles = 2;</code>
     */
    public org.mrk.grpc.catalog.Bundle getBundles(int index) {
      if (bundlesBuilder_ == null) {
        return bundles_.get(index);
      } else {
        return bundlesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Bundle bundles = 2;</code>
     */
    public Builder setBundles(
        int index, org.mrk.grpc.catalog.Bundle value) {
      if (bundlesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBundlesIsMutable();
        bundles_.set(index, value);
        onChanged();
      } else {
        bundlesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Bundle bundles = 2;</code>
     */
    public Builder setBundles(
        int index, org.mrk.grpc.catalog.Bundle.Builder builderForValue) {
      if (bundlesBuilder_ == null) {
        ensureBundlesIsMutable();
        bundles_.set(index, builderForValue.build());
        onChanged();
      } else {
        bundlesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Bundle bundles = 2;</code>
     */
    public Builder addBundles(org.mrk.grpc.catalog.Bundle value) {
      if (bundlesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBundlesIsMutable();
        bundles_.add(value);
        onChanged();
      } else {
        bundlesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Bundle bundles = 2;</code>
     */
    public Builder addBundles(
        int index, org.mrk.grpc.catalog.Bundle value) {
      if (bundlesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBundlesIsMutable();
        bundles_.add(index, value);
        onChanged();
      } else {
        bundlesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Bundle bundles = 2;</code>
     */
    public Builder addBundles(
        org.mrk.grpc.catalog.Bundle.Builder builderForValue) {
      if (bundlesBuilder_ == null) {
        ensureBundlesIsMutable();
        bundles_.add(builderForValue.build());
        onChanged();
      } else {
        bundlesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Bundle bundles = 2;</code>
     */
    public Builder addBundles(
        int index, org.mrk.grpc.catalog.Bundle.Builder builderForValue) {
      if (bundlesBuilder_ == null) {
        ensureBundlesIsMutable();
        bundles_.add(index, builderForValue.build());
        onChanged();
      } else {
        bundlesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Bundle bundles = 2;</code>
     */
    public Builder addAllBundles(
        java.lang.Iterable<? extends org.mrk.grpc.catalog.Bundle> values) {
      if (bundlesBuilder_ == null) {
        ensureBundlesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, bundles_);
        onChanged();
      } else {
        bundlesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Bundle bundles = 2;</code>
     */
    public Builder clearBundles() {
      if (bundlesBuilder_ == null) {
        bundles_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        bundlesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Bundle bundles = 2;</code>
     */
    public Builder removeBundles(int index) {
      if (bundlesBuilder_ == null) {
        ensureBundlesIsMutable();
        bundles_.remove(index);
        onChanged();
      } else {
        bundlesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Bundle bundles = 2;</code>
     */
    public org.mrk.grpc.catalog.Bundle.Builder getBundlesBuilder(
        int index) {
      return getBundlesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Bundle bundles = 2;</code>
     */
    public org.mrk.grpc.catalog.BundleOrBuilder getBundlesOrBuilder(
        int index) {
      if (bundlesBuilder_ == null) {
        return bundles_.get(index);  } else {
        return bundlesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Bundle bundles = 2;</code>
     */
    public java.util.List<? extends org.mrk.grpc.catalog.BundleOrBuilder> 
         getBundlesOrBuilderList() {
      if (bundlesBuilder_ != null) {
        return bundlesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(bundles_);
      }
    }
    /**
     * <code>repeated .Bundle bundles = 2;</code>
     */
    public org.mrk.grpc.catalog.Bundle.Builder addBundlesBuilder() {
      return getBundlesFieldBuilder().addBuilder(
          org.mrk.grpc.catalog.Bundle.getDefaultInstance());
    }
    /**
     * <code>repeated .Bundle bundles = 2;</code>
     */
    public org.mrk.grpc.catalog.Bundle.Builder addBundlesBuilder(
        int index) {
      return getBundlesFieldBuilder().addBuilder(
          index, org.mrk.grpc.catalog.Bundle.getDefaultInstance());
    }
    /**
     * <code>repeated .Bundle bundles = 2;</code>
     */
    public java.util.List<org.mrk.grpc.catalog.Bundle.Builder> 
         getBundlesBuilderList() {
      return getBundlesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.mrk.grpc.catalog.Bundle, org.mrk.grpc.catalog.Bundle.Builder, org.mrk.grpc.catalog.BundleOrBuilder> 
        getBundlesFieldBuilder() {
      if (bundlesBuilder_ == null) {
        bundlesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.mrk.grpc.catalog.Bundle, org.mrk.grpc.catalog.Bundle.Builder, org.mrk.grpc.catalog.BundleOrBuilder>(
                bundles_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        bundles_ = null;
      }
      return bundlesBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:CatalogItem)
  }

  // @@protoc_insertion_point(class_scope:CatalogItem)
  private static final org.mrk.grpc.catalog.CatalogItem DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.mrk.grpc.catalog.CatalogItem();
  }

  public static org.mrk.grpc.catalog.CatalogItem getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CatalogItem>
      PARSER = new com.google.protobuf.AbstractParser<CatalogItem>() {
    public CatalogItem parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new CatalogItem(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CatalogItem> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CatalogItem> getParserForType() {
    return PARSER;
  }

  public org.mrk.grpc.catalog.CatalogItem getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

