// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catalog.proto

package org.mrk.grpc.catalog;

/**
 * Protobuf type {@code Catalog}
 */
public  final class Catalog extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Catalog)
    CatalogOrBuilder {
  // Use Catalog.newBuilder() to construct.
  private Catalog(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Catalog() {
    catalogId_ = "";
    catalogName_ = "";
    catalogItems_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Catalog(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            catalogId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            catalogName_ = s;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              catalogItems_ = new java.util.ArrayList<org.mrk.grpc.catalog.CatalogItem>();
              mutable_bitField0_ |= 0x00000004;
            }
            catalogItems_.add(
                input.readMessage(org.mrk.grpc.catalog.CatalogItem.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        catalogItems_ = java.util.Collections.unmodifiableList(catalogItems_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.mrk.grpc.catalog.CatalogProto.internal_static_Catalog_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.mrk.grpc.catalog.CatalogProto.internal_static_Catalog_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.mrk.grpc.catalog.Catalog.class, org.mrk.grpc.catalog.Catalog.Builder.class);
  }

  private int bitField0_;
  public static final int CATALOGID_FIELD_NUMBER = 1;
  private volatile java.lang.Object catalogId_;
  /**
   * <code>optional string catalogId = 1;</code>
   */
  public java.lang.String getCatalogId() {
    java.lang.Object ref = catalogId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      catalogId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string catalogId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getCatalogIdBytes() {
    java.lang.Object ref = catalogId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      catalogId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CATALOGNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object catalogName_;
  /**
   * <code>optional string catalogName = 2;</code>
   */
  public java.lang.String getCatalogName() {
    java.lang.Object ref = catalogName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      catalogName_ = s;
      return s;
    }
  }
  /**
   * <code>optional string catalogName = 2;</code>
   */
  public com.google.protobuf.ByteString
      getCatalogNameBytes() {
    java.lang.Object ref = catalogName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      catalogName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CATALOGITEMS_FIELD_NUMBER = 3;
  private java.util.List<org.mrk.grpc.catalog.CatalogItem> catalogItems_;
  /**
   * <code>repeated .CatalogItem catalogItems = 3;</code>
   */
  public java.util.List<org.mrk.grpc.catalog.CatalogItem> getCatalogItemsList() {
    return catalogItems_;
  }
  /**
   * <code>repeated .CatalogItem catalogItems = 3;</code>
   */
  public java.util.List<? extends org.mrk.grpc.catalog.CatalogItemOrBuilder> 
      getCatalogItemsOrBuilderList() {
    return catalogItems_;
  }
  /**
   * <code>repeated .CatalogItem catalogItems = 3;</code>
   */
  public int getCatalogItemsCount() {
    return catalogItems_.size();
  }
  /**
   * <code>repeated .CatalogItem catalogItems = 3;</code>
   */
  public org.mrk.grpc.catalog.CatalogItem getCatalogItems(int index) {
    return catalogItems_.get(index);
  }
  /**
   * <code>repeated .CatalogItem catalogItems = 3;</code>
   */
  public org.mrk.grpc.catalog.CatalogItemOrBuilder getCatalogItemsOrBuilder(
      int index) {
    return catalogItems_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getCatalogIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, catalogId_);
    }
    if (!getCatalogNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, catalogName_);
    }
    for (int i = 0; i < catalogItems_.size(); i++) {
      output.writeMessage(3, catalogItems_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCatalogIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, catalogId_);
    }
    if (!getCatalogNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, catalogName_);
    }
    for (int i = 0; i < catalogItems_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, catalogItems_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.mrk.grpc.catalog.Catalog)) {
      return super.equals(obj);
    }
    org.mrk.grpc.catalog.Catalog other = (org.mrk.grpc.catalog.Catalog) obj;

    boolean result = true;
    result = result && getCatalogId()
        .equals(other.getCatalogId());
    result = result && getCatalogName()
        .equals(other.getCatalogName());
    result = result && getCatalogItemsList()
        .equals(other.getCatalogItemsList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + CATALOGID_FIELD_NUMBER;
    hash = (53 * hash) + getCatalogId().hashCode();
    hash = (37 * hash) + CATALOGNAME_FIELD_NUMBER;
    hash = (53 * hash) + getCatalogName().hashCode();
    if (getCatalogItemsCount() > 0) {
      hash = (37 * hash) + CATALOGITEMS_FIELD_NUMBER;
      hash = (53 * hash) + getCatalogItemsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.mrk.grpc.catalog.Catalog parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mrk.grpc.catalog.Catalog parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mrk.grpc.catalog.Catalog parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mrk.grpc.catalog.Catalog parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mrk.grpc.catalog.Catalog parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mrk.grpc.catalog.Catalog parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mrk.grpc.catalog.Catalog parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.mrk.grpc.catalog.Catalog parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mrk.grpc.catalog.Catalog parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mrk.grpc.catalog.Catalog parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.mrk.grpc.catalog.Catalog prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Catalog}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Catalog)
      org.mrk.grpc.catalog.CatalogOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.mrk.grpc.catalog.CatalogProto.internal_static_Catalog_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.mrk.grpc.catalog.CatalogProto.internal_static_Catalog_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.mrk.grpc.catalog.Catalog.class, org.mrk.grpc.catalog.Catalog.Builder.class);
    }

    // Construct using org.mrk.grpc.catalog.Catalog.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCatalogItemsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      catalogId_ = "";

      catalogName_ = "";

      if (catalogItemsBuilder_ == null) {
        catalogItems_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        catalogItemsBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.mrk.grpc.catalog.CatalogProto.internal_static_Catalog_descriptor;
    }

    public org.mrk.grpc.catalog.Catalog getDefaultInstanceForType() {
      return org.mrk.grpc.catalog.Catalog.getDefaultInstance();
    }

    public org.mrk.grpc.catalog.Catalog build() {
      org.mrk.grpc.catalog.Catalog result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.mrk.grpc.catalog.Catalog buildPartial() {
      org.mrk.grpc.catalog.Catalog result = new org.mrk.grpc.catalog.Catalog(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.catalogId_ = catalogId_;
      result.catalogName_ = catalogName_;
      if (catalogItemsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          catalogItems_ = java.util.Collections.unmodifiableList(catalogItems_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.catalogItems_ = catalogItems_;
      } else {
        result.catalogItems_ = catalogItemsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.mrk.grpc.catalog.Catalog) {
        return mergeFrom((org.mrk.grpc.catalog.Catalog)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.mrk.grpc.catalog.Catalog other) {
      if (other == org.mrk.grpc.catalog.Catalog.getDefaultInstance()) return this;
      if (!other.getCatalogId().isEmpty()) {
        catalogId_ = other.catalogId_;
        onChanged();
      }
      if (!other.getCatalogName().isEmpty()) {
        catalogName_ = other.catalogName_;
        onChanged();
      }
      if (catalogItemsBuilder_ == null) {
        if (!other.catalogItems_.isEmpty()) {
          if (catalogItems_.isEmpty()) {
            catalogItems_ = other.catalogItems_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureCatalogItemsIsMutable();
            catalogItems_.addAll(other.catalogItems_);
          }
          onChanged();
        }
      } else {
        if (!other.catalogItems_.isEmpty()) {
          if (catalogItemsBuilder_.isEmpty()) {
            catalogItemsBuilder_.dispose();
            catalogItemsBuilder_ = null;
            catalogItems_ = other.catalogItems_;
            bitField0_ = (bitField0_ & ~0x00000004);
            catalogItemsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCatalogItemsFieldBuilder() : null;
          } else {
            catalogItemsBuilder_.addAllMessages(other.catalogItems_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.mrk.grpc.catalog.Catalog parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.mrk.grpc.catalog.Catalog) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object catalogId_ = "";
    /**
     * <code>optional string catalogId = 1;</code>
     */
    public java.lang.String getCatalogId() {
      java.lang.Object ref = catalogId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        catalogId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string catalogId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCatalogIdBytes() {
      java.lang.Object ref = catalogId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        catalogId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string catalogId = 1;</code>
     */
    public Builder setCatalogId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      catalogId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string catalogId = 1;</code>
     */
    public Builder clearCatalogId() {
      
      catalogId_ = getDefaultInstance().getCatalogId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string catalogId = 1;</code>
     */
    public Builder setCatalogIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      catalogId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object catalogName_ = "";
    /**
     * <code>optional string catalogName = 2;</code>
     */
    public java.lang.String getCatalogName() {
      java.lang.Object ref = catalogName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        catalogName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string catalogName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCatalogNameBytes() {
      java.lang.Object ref = catalogName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        catalogName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string catalogName = 2;</code>
     */
    public Builder setCatalogName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      catalogName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string catalogName = 2;</code>
     */
    public Builder clearCatalogName() {
      
      catalogName_ = getDefaultInstance().getCatalogName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string catalogName = 2;</code>
     */
    public Builder setCatalogNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      catalogName_ = value;
      onChanged();
      return this;
    }

    private java.util.List<org.mrk.grpc.catalog.CatalogItem> catalogItems_ =
      java.util.Collections.emptyList();
    private void ensureCatalogItemsIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        catalogItems_ = new java.util.ArrayList<org.mrk.grpc.catalog.CatalogItem>(catalogItems_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.mrk.grpc.catalog.CatalogItem, org.mrk.grpc.catalog.CatalogItem.Builder, org.mrk.grpc.catalog.CatalogItemOrBuilder> catalogItemsBuilder_;

    /**
     * <code>repeated .CatalogItem catalogItems = 3;</code>
     */
    public java.util.List<org.mrk.grpc.catalog.CatalogItem> getCatalogItemsList() {
      if (catalogItemsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(catalogItems_);
      } else {
        return catalogItemsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .CatalogItem catalogItems = 3;</code>
     */
    public int getCatalogItemsCount() {
      if (catalogItemsBuilder_ == null) {
        return catalogItems_.size();
      } else {
        return catalogItemsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .CatalogItem catalogItems = 3;</code>
     */
    public org.mrk.grpc.catalog.CatalogItem getCatalogItems(int index) {
      if (catalogItemsBuilder_ == null) {
        return catalogItems_.get(index);
      } else {
        return catalogItemsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .CatalogItem catalogItems = 3;</code>
     */
    public Builder setCatalogItems(
        int index, org.mrk.grpc.catalog.CatalogItem value) {
      if (catalogItemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCatalogItemsIsMutable();
        catalogItems_.set(index, value);
        onChanged();
      } else {
        catalogItemsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .CatalogItem catalogItems = 3;</code>
     */
    public Builder setCatalogItems(
        int index, org.mrk.grpc.catalog.CatalogItem.Builder builderForValue) {
      if (catalogItemsBuilder_ == null) {
        ensureCatalogItemsIsMutable();
        catalogItems_.set(index, builderForValue.build());
        onChanged();
      } else {
        catalogItemsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CatalogItem catalogItems = 3;</code>
     */
    public Builder addCatalogItems(org.mrk.grpc.catalog.CatalogItem value) {
      if (catalogItemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCatalogItemsIsMutable();
        catalogItems_.add(value);
        onChanged();
      } else {
        catalogItemsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .CatalogItem catalogItems = 3;</code>
     */
    public Builder addCatalogItems(
        int index, org.mrk.grpc.catalog.CatalogItem value) {
      if (catalogItemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCatalogItemsIsMutable();
        catalogItems_.add(index, value);
        onChanged();
      } else {
        catalogItemsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .CatalogItem catalogItems = 3;</code>
     */
    public Builder addCatalogItems(
        org.mrk.grpc.catalog.CatalogItem.Builder builderForValue) {
      if (catalogItemsBuilder_ == null) {
        ensureCatalogItemsIsMutable();
        catalogItems_.add(builderForValue.build());
        onChanged();
      } else {
        catalogItemsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CatalogItem catalogItems = 3;</code>
     */
    public Builder addCatalogItems(
        int index, org.mrk.grpc.catalog.CatalogItem.Builder builderForValue) {
      if (catalogItemsBuilder_ == null) {
        ensureCatalogItemsIsMutable();
        catalogItems_.add(index, builderForValue.build());
        onChanged();
      } else {
        catalogItemsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CatalogItem catalogItems = 3;</code>
     */
    public Builder addAllCatalogItems(
        java.lang.Iterable<? extends org.mrk.grpc.catalog.CatalogItem> values) {
      if (catalogItemsBuilder_ == null) {
        ensureCatalogItemsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, catalogItems_);
        onChanged();
      } else {
        catalogItemsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .CatalogItem catalogItems = 3;</code>
     */
    public Builder clearCatalogItems() {
      if (catalogItemsBuilder_ == null) {
        catalogItems_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        catalogItemsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .CatalogItem catalogItems = 3;</code>
     */
    public Builder removeCatalogItems(int index) {
      if (catalogItemsBuilder_ == null) {
        ensureCatalogItemsIsMutable();
        catalogItems_.remove(index);
        onChanged();
      } else {
        catalogItemsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .CatalogItem catalogItems = 3;</code>
     */
    public org.mrk.grpc.catalog.CatalogItem.Builder getCatalogItemsBuilder(
        int index) {
      return getCatalogItemsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .CatalogItem catalogItems = 3;</code>
     */
    public org.mrk.grpc.catalog.CatalogItemOrBuilder getCatalogItemsOrBuilder(
        int index) {
      if (catalogItemsBuilder_ == null) {
        return catalogItems_.get(index);  } else {
        return catalogItemsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .CatalogItem catalogItems = 3;</code>
     */
    public java.util.List<? extends org.mrk.grpc.catalog.CatalogItemOrBuilder> 
         getCatalogItemsOrBuilderList() {
      if (catalogItemsBuilder_ != null) {
        return catalogItemsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(catalogItems_);
      }
    }
    /**
     * <code>repeated .CatalogItem catalogItems = 3;</code>
     */
    public org.mrk.grpc.catalog.CatalogItem.Builder addCatalogItemsBuilder() {
      return getCatalogItemsFieldBuilder().addBuilder(
          org.mrk.grpc.catalog.CatalogItem.getDefaultInstance());
    }
    /**
     * <code>repeated .CatalogItem catalogItems = 3;</code>
     */
    public org.mrk.grpc.catalog.CatalogItem.Builder addCatalogItemsBuilder(
        int index) {
      return getCatalogItemsFieldBuilder().addBuilder(
          index, org.mrk.grpc.catalog.CatalogItem.getDefaultInstance());
    }
    /**
     * <code>repeated .CatalogItem catalogItems = 3;</code>
     */
    public java.util.List<org.mrk.grpc.catalog.CatalogItem.Builder> 
         getCatalogItemsBuilderList() {
      return getCatalogItemsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.mrk.grpc.catalog.CatalogItem, org.mrk.grpc.catalog.CatalogItem.Builder, org.mrk.grpc.catalog.CatalogItemOrBuilder> 
        getCatalogItemsFieldBuilder() {
      if (catalogItemsBuilder_ == null) {
        catalogItemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.mrk.grpc.catalog.CatalogItem, org.mrk.grpc.catalog.CatalogItem.Builder, org.mrk.grpc.catalog.CatalogItemOrBuilder>(
                catalogItems_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        catalogItems_ = null;
      }
      return catalogItemsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:Catalog)
  }

  // @@protoc_insertion_point(class_scope:Catalog)
  private static final org.mrk.grpc.catalog.Catalog DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.mrk.grpc.catalog.Catalog();
  }

  public static org.mrk.grpc.catalog.Catalog getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Catalog>
      PARSER = new com.google.protobuf.AbstractParser<Catalog>() {
    public Catalog parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Catalog(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Catalog> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Catalog> getParserForType() {
    return PARSER;
  }

  public org.mrk.grpc.catalog.Catalog getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

