// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catalog.proto

package org.mrk.grpc.catalog;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Empty)
    com.google.protobuf.MessageOrBuilder {
}
