// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catalog.proto

package org.mrk.grpc.catalog;

public interface ProductOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Product)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string code = 2;</code>
   */
  java.lang.String getCode();
  /**
   * <code>optional string code = 2;</code>
   */
  com.google.protobuf.ByteString
      getCodeBytes();
}
