// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catalog.proto

package org.mrk.grpc.catalog;

public interface SearchRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SearchRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string catalogName = 1;</code>
   */
  java.lang.String getCatalogName();
  /**
   * <code>optional string catalogName = 1;</code>
   */
  com.google.protobuf.ByteString
      getCatalogNameBytes();

  /**
   * <code>optional string productName = 2;</code>
   */
  java.lang.String getProductName();
  /**
   * <code>optional string productName = 2;</code>
   */
  com.google.protobuf.ByteString
      getProductNameBytes();
}
